[project]
org-name= "collibra"
version= "0.1.23"
authors = ["wbvreeuwijk"]
repository = "https://github.com/wbvreeuwijk/collibra-ballerina-dgc"
keywords = ["collibra","data governance","dgc","jdbc"]
license = ["Apache-2.0"]

[platform]
target = "java8"

[dependencies]
