[project]
org-name= "collibra"
version= "0.1.1"

[platform]
target = "java8"

    [[platform.libraries]]
    artafactId = "mssql-connector-java"
    version = "7.4.1"
    path = "./lib/mssql-jdbc-7.4.1.jre8.jar"
    groupId = "mssql"
    modules = ["ms.jdbc.extractor","generic.jdbc.extractor"]


[dependencies]
